spring.application.name=SGTX

# MySQL Settings
spring.datasource.url=jdbc:mysql://zephyr.proxy.rlwy.net:25145/railway
spring.datasource.username=root
spring.datasource.password=hFDVMWqulPQDhfgiOYEFUCcsUZBmMzZS

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# H2 Database Settings (for local development - commented out)
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true
